# Generated by Django 2.1.1 on 2018-09-20 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=32)),
                ('hour', models.CharField(max_length=16)),
                ('conzone_id', models.CharField(max_length=64)),
                ('road_type', models.CharField(max_length=16)),
                ('traffic_vol', models.CharField(max_length=16)),
            ],
        ),
    ]
