# Generated by Django 2.1.1 on 2018-09-22 07:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_roaddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=32)),
                ('hour', models.CharField(max_length=16)),
                ('start_id', models.CharField(max_length=64)),
                ('end_id', models.CharField(max_length=64)),
                ('pass_time', models.CharField(max_length=16)),
            ],
        ),
        migrations.RenameField(
            model_name='roaddata',
            old_name='conzone_id',
            new_name='end_id',
        ),
        migrations.RenameField(
            model_name='roaddata',
            old_name='traffic_vol',
            new_name='pass_time',
        ),
        migrations.AddField(
            model_name='roaddata',
            name='start_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
    ]
