# Generated by Django 2.1.1 on 2018-09-22 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180922_1647'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrafficData',
        ),
        migrations.RemoveField(
            model_name='roaddata',
            name='road_type',
        ),
    ]
